'''
supplementary.py
there should be 1 inputs, provider list

Answered Question:
Q7: How many items are contributed by each dataProvider?
Q8: Are there any dataProviders who contribute items to more than one provider?
'''
import sys
import dpla_utils
import getopt, dpla_config
import csv
import argparse


PROVIDER_HEADER_PROVIDER_NAME = 'provider.name' 
PROVIDER_HEADER_ITEMS_COUNT = 'count_of_items'
PROVIDER_HEADER_DATAPROVIDER_PATH = 'dataProvider_file_path'
EXPECTED_INPUT_HEADER = [PROVIDER_HEADER_PROVIDER_NAME, PROVIDER_HEADER_ITEMS_COUNT, PROVIDER_HEADER_DATAPROVIDER_PATH]

def supplementary():
	parser = argparse.ArgumentParser()
	parser.add_argument('-i', action='append', dest = 'provider_input_file', help = 'A provider list file generated by both set_provider_list.py and set_dataprovider_list.py is needed')
	#parser.add_argument('-e', action = 'append', dest = 'output_file_dir')
	results = parser.parse_args()
	
	provider_file = results.provider_input_file[0]
	#collection_file = results.input_file_list[1] # does this work?

	#dataProvider_dir = results.output_file_dir[0] # should be 'files/dataProvider/'
	dataProvider_list = []
	repeated_dataProvider_list = []
	try:

		#process_provider_list(provider_file)
		with open(provider_file) as provider_input_file:
			provider_csv_reader = csv.reader(provider_input_file)

			#check input header
			input_header = next(provider_csv_reader, None)
			if not input_header == EXPECTED_INPUT_HEADER:
				print("input header doesn`t match")
				sys.exit()

			print("**************Q7: How many items are contributed by each dataProvider *************")

			for provider_information_row in provider_csv_reader:
				dataProvider_file_path = provider_information_row[2]

				#read dataProvider files
				with open(dataProvider_file_path) as dataProvider_input_file:
					dataProvider_csv_reader = csv.reader(dataProvider_input_file)

					#skip the header
					skip_header = next(dataProvider_csv_reader, None)

					# traverse each dataProvider list
					for dataProvider_information_row in dataProvider_csv_reader:
						current_dataProvider_name = dataProvider_information_row[0]
						#if repeated
						if current_dataProvider_name in dataProvider_list:
							if not current_dataProvider_name in repeated_dataProvider_list:
								repeated_dataProvider_list.append(current_dataProvider_name)
						# if not repeated
						else:
							# Question: How many items are contributed by each dataProvider?
							print("dataProvider ", current_dataProvider_name, " contributes ", dataProvider_information_row[1], " items")

							dataProvider_list.append(current_dataProvider_name)

				dataProvider_input_file.close()
		provider_input_file.close()

		#Question: Are there any dataProviders who contribute items to more than one provider?
		print("**************Q8: Are there any dataProviders who contribute items to more than one provider? *************")
		print(repeated_dataProvider_list)
	except IOError as provider_input_file_error:
		print("couldn`t read the input file ") 


supplementary()



